server:
  port: 8080


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: user
    password: user

    hikari:
      pool-name: Claim-Assignment-Pool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    root: info
    com.example.claim: debug
    org.hibernate.orm.jdbc.bind: trace